# Custom Jekyll Setting
title: UnblockMedium
tagline: 'A Daily Report'
description: 'A Daily Report on Medium Malaysia Censorship'
email: unblockmedium@gmail.com
baseurl: ""
url: 'https://unblockmedium.com'
enforce_ssl: 'unblockmedium.com'

paginate: 15
markdown: Kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Navigator 
navigation:
 - title: Home
   url: /
 - title: About
   url: /about/
 - title: Worth the Read
   url: /read/
   
# Social
twitter_handle: UnblockMedium
facebook_community: UnblockMedium     

# Precious Gems
gems:
  - jekyll-sitemap
  
author:
  name: 'UnblockMedium'
  url: https://unblockmedium.com
  
version: 1.0.0
