# Custom Jekyll Setting
title: UnblockMedium
tagline: 'A Daily Report'
description: 'A Daily Report on Medium Malaysia Censorship'
email: unblockmedium@gmail.com
baseurl: ""
url: 'https://unblockmedium.com'
enforce_ssl: 'unblockmedium.com'

paginate: 1
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

#Navigator 
navigation:
 - title: Home
   url: /
 - title: About
   url: /about/ 
 - title: DNS List
   url: /dns/

#Precious Gems
gems:
  - jekyll-sitemap
  
author:
  name: 'UnblockMedium'
  url: https://twitter.com/hashtag/UnblockMedium
  
version: 1.0.0
